name: "Module CI/CD"

on:
  release:
    types: [created]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  PROJECT_NAME: G2OWS

jobs:
  build-windows:
    name: Build Windows (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure
        run: cmake . --preset Windows-${{ matrix.arch }}-Release

      - name: Build
        run: cmake --build --preset Windows-${{ matrix.arch }}-Release

      - name: Copy module
        run: copy out\\build\\Windows-${{ matrix.arch }}-Release\\${{ env.PROJECT_NAME }}.${{ matrix.arch }}.dll .
        
      - name: Archive module
        run: Compress-Archive -Path "g2ows.json", "${{ env.PROJECT_NAME }}.${{ matrix.arch }}.dll" -Destination ${{ env.PROJECT_NAME }}.${{ matrix.arch }}.zip
      
      - name: Upload module
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PROJECT_NAME }}.${{ matrix.arch }}.dll

  build-linux:
    name: Build Linux (${{ matrix.arch }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x64, arm, arm64]
    container:
      image: registry.gitlab.com/gothicmultiplayerteam/buildimage:ubuntu-20.04-x64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake . --preset Linux-${{ matrix.arch }}-Release

      - name: Build
        run: cmake --build --preset Linux-${{ matrix.arch }}-Release

      - name: Copy module
        run: cp out/build/Linux-${{ matrix.arch }}-Release/${{ env.PROJECT_NAME }}.${{ matrix.arch }}.so ./
      
      - name: Archive module
        uses: montudor/action-zip@v1
        with:
          args: zip -r ${{ env.PROJECT_NAME }}.${{ matrix.arch }}.zip g2ows.json ${{ env.PROJECT_NAME }}.${{ matrix.arch }}.so
      
      - name: Upload module
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PROJECT_NAME }}.${{ matrix.arch }}.zip